[General]
__userfile__=true
size=@Size(600 400)

[SavedConfigs]
SavedSettings\1\date=2026-09-23T00:10:35
SavedSettings\1\name=Wed Sep 23 00:10:35 2026
SavedSettings\1\settings\1\connected=true
SavedSettings\1\settings\1\currentMode=87
SavedSettings\1\settings\1\currentModeHeight=1080
SavedSettings\1\settings\1\currentModeRate=60.00316619873047
SavedSettings\1\settings\1\currentModeWidth=1920
SavedSettings\1\settings\1\enabled=false
SavedSettings\1\settings\1\hash=56f6f61b0c60fb5b5b4a7953e1d56af0
SavedSettings\1\settings\1\name=eDP
SavedSettings\1\settings\1\primary=true
SavedSettings\1\settings\1\rotation=1
SavedSettings\1\settings\1\xPos=0
SavedSettings\1\settings\1\yPos=0
SavedSettings\1\settings\2\connected=true
SavedSettings\1\settings\2\currentMode=97
SavedSettings\1\settings\2\currentModeHeight=1200
SavedSettings\1\settings\2\currentModeRate=59.950172424316406
SavedSettings\1\settings\2\currentModeWidth=1920
SavedSettings\1\settings\2\enabled=true
SavedSettings\1\settings\2\hash=fca5f3e8cf13676e06dbd0d1eb0c1998
SavedSettings\1\settings\2\name=HDMI-A-0
SavedSettings\1\settings\2\primary=false
SavedSettings\1\settings\2\rotation=1
SavedSettings\1\settings\2\xPos=0
SavedSettings\1\settings\2\yPos=0
SavedSettings\1\settings\3\connected=false
SavedSettings\1\settings\3\hash=
SavedSettings\1\settings\3\name=DisplayPort-0
SavedSettings\1\settings\4\connected=false
SavedSettings\1\settings\4\hash=
SavedSettings\1\settings\4\name=DisplayPort-1
SavedSettings\1\settings\size=4
SavedSettings\size=1

[currentConfig]
settings\1\connected=true
settings\1\currentMode=87
settings\1\currentModeHeight=1080
settings\1\currentModeRate=60.00316619873047
settings\1\currentModeWidth=1920
settings\1\enabled=false
settings\1\hash=56f6f61b0c60fb5b5b4a7953e1d56af0
settings\1\name=eDP
settings\1\primary=true
settings\1\rotation=1
settings\1\xPos=0
settings\1\yPos=0
settings\2\connected=true
settings\2\currentMode=97
settings\2\currentModeHeight=1200
settings\2\currentModeRate=59.950172424316406
settings\2\currentModeWidth=1920
settings\2\enabled=true
settings\2\hash=fca5f3e8cf13676e06dbd0d1eb0c1998
settings\2\name=HDMI-A-0
settings\2\primary=false
settings\2\rotation=1
settings\2\xPos=0
settings\2\yPos=0
settings\3\connected=false
settings\3\hash=
settings\3\name=DisplayPort-0
settings\4\connected=false
settings\4\hash=
settings\4\name=DisplayPort-1
settings\size=4
