[General]
__userfile__=true
panels=panel1

[fancymenu]
alignment=Right
categoriesAtRight=true
filterClear=true

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=32
plugins=fancymenu, spacer, statusnotifier, mount, volume, worldclock
position=Bottom
reserve-space=true
screen-name=HDMI-A-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[spacer]
alignment=Left
expandable=true
spaceType=invisible
type=spacer

[volume]
alignment=Right

[worldclock]
alignment=Right
