[General]
__userfile__=true

[desktopswitch]
alignment=Left
showOnlyActive=true

[mainmenu]
alignment=Left
type=mainmenu

[mount]
alignment=Right

[panel1]
plugins=mainmenu, desktopswitch, spacer, statusnotifier, tray, mount, volume, worldclock

[spacer]
alignment=Left
expandable=true
spaceType=invisible
type=spacer

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
